#!/usr/bin/env python3
"""
Topological Generation – Creatio ex Nihilo for APEIRON
========================================================
Optional module for Layer 2.

Detects "holes" in the hypergraph's simplicial complex and generates
hypothetical observables that fill them. Uses the Yoneda embedding
in reverse: a representable functor not yet realised by an existing
object defines a new object that *ought* to exist to make the category
idempotent‑complete. This allows the AI to generate structure where
no data exists, driven purely by topological and categorical
necessity.

Mathematical Foundation
-----------------------
Let C be the RelationalCategory of the hypergraph. The Yoneda embedding
y : C → [Cᵒᵖ, Set] sends each object X to the representable functor
hom(-, X). A functor F : Cᵒᵖ → Set is representable if F ≅ y(X) for
some X. If the nerve of C has "missing simplices", there exist
compatible families of morphisms that are not generated by any single
object. These correspond to non‑representable functors. Adding a new
object that represents such a functor completes the category.

Algorithm:
1. Compute the nerve of C up to dimension 2 (vertices, edges, triangles).
2. Identify "missing triangles": triples of vertices that are pairwise
   connected but do not span a 2‑simplex.
3. Create a new vertex (the "filler") and connect it to the three vertices
   of the missing triangle via appropriate morphisms, satisfying the
   universal property of a colimit (a "join" of the three vertices).
4. Add the new vertex and its relations to the hypergraph.

The effect is a mathematically minimal extension that restores the
Euler characteristic or homotopy type of the knowledge space.

References
----------
.. [1] Mac Lane, S. "Categories for the Working Mathematician" (1971)
.. [2] Beniers, D. "17 Layers AI Model" (2025)
.. [3] Spivak, D.I. "Functorial Data Migration" (2012)
"""

import numpy as np
from typing import Dict, List, Tuple, Set, Optional, Any
from dataclasses import dataclass, field
from itertools import combinations

try:
    from apeiron.layers.layer02_relational.hypergraph import Hypergraph
except ImportError:
    Hypergraph = None

try:
    from apeiron.layers.layer02_relational.category import RelationalCategory
except ImportError:
    RelationalCategory = None


@dataclass
class MissingSimplex:
    """
    A missing simplex in the nerve of the category.

    Attributes:
        dimension: the dimension of the missing simplex (e.g., 2 for triangle).
        vertices: the vertices that would form the simplex.
        edges: the existing edges among these vertices.
        description: human‑readable label.
    """
    dimension: int
    vertices: Set[Any]
    edges: List[Tuple[Any, Any]]
    description: str


class TopologicalGenerator:
    """
    Detects topological gaps and generates new vertices and hyperedges
    to fill them.

    Parameters
    ----------
    hypergraph : Hypergraph
        The current knowledge hypergraph.
    category : RelationalCategory, optional
        The current category structure. If None, it is built from the hypergraph.
    max_generations : int
        Maximum number of new concepts to generate per run.
    """

    def __init__(self, hypergraph, category=None, max_generations: int = 10):
        if Hypergraph is None:
            raise ImportError("Hypergraph module is required.")
        self.hypergraph = hypergraph
        self.category = category
        self.max_generations = max_generations
        if self.category is None and RelationalCategory is not None:
            self.category = self._build_category()

    def _build_category(self) -> Optional[Any]:
        """Build a RelationalCategory from the hypergraph."""
        if RelationalCategory is None:
            return None
        cat = RelationalCategory()
        for v in self.hypergraph.vertices:
            cat.add_object(v)
        for eid, edge in self.hypergraph.hyperedges.items():
            verts = list(edge)
            for i in range(len(verts)):
                for j in range(i + 1, len(verts)):
                    cat.add_morphism(verts[i], verts[j], f"{eid}_{verts[i]}_{verts[j]}")
                    cat.add_morphism(verts[j], verts[i], f"{eid}_{verts[j]}_{verts[i]}")
        return cat

    def detect_missing_simplices(self, max_dim: int = 2) -> List[MissingSimplex]:
        """
        Detect missing simplices in the nerve of the category.

        A missing n‑simplex is a set of n+1 vertices that are completely
        pairwise connected (i.e., form a clique) but do not appear together
        in any hyperedge of size ≥ n+1.

        Returns a list of MissingSimplex objects.
        """
        missing = []
        vertices = list(self.hypergraph.vertices)
        if len(vertices) < 3:
            return missing

        # Build adjacency (clique graph)
        adjacency = {v: set() for v in vertices}
        for edge in self.hypergraph.hyperedges.values():
            for u, v in combinations(edge, 2):
                adjacency[u].add(v)
                adjacency[v].add(u)

        # Find all 2‑dimensional missing simplices (triangles)
        for triple in combinations(vertices, 3):
            v1, v2, v3 = triple
            # Check if they form a clique (all pairwise connected)
            if (v2 in adjacency[v1] and v3 in adjacency[v1] and
                v3 in adjacency[v2]):
                # Check if there is already a hyperedge containing all three
                covered = False
                for edge in self.hypergraph.hyperedges.values():
                    if {v1, v2, v3}.issubset(edge):
                        covered = True
                        break
                if not covered:
                    edges = [(v1, v2), (v1, v3), (v2, v3)]
                    missing.append(MissingSimplex(
                        dimension=2,
                        vertices={v1, v2, v3},
                        edges=edges,
                        description=f"Missing triangle: {v1}, {v2}, {v3} form a clique but no 2‑simplex"
                    ))
        return missing

    def generate_filler(self, simplex: MissingSimplex) -> Dict[str, Any]:
        """
        Generate a new vertex and relations that fill the missing simplex.

        The new vertex is the colimit (join) of the vertices of the simplex.
        In the hypergraph, this translates to adding a new vertex and
        hyperedges connecting it to all vertices of the missing simplex.

        Parameters
        ----------
        simplex : MissingSimplex

        Returns
        -------
        dict with keys: 'new_vertex', 'new_hyperedges', 'new_morphisms'
        """
        verts = sorted(simplex.vertices)
        new_vertex = f"Yoneda_filler_{hash(frozenset(verts)) % 100000}"

        # Hyperedges: connect the new vertex to all vertices of the simplex
        new_hyperedges = [set(verts) | {new_vertex}]

        # Morphisms (if category is available):
        # For each vertex v in the simplex, add a morphism v → new_vertex
        # (the coprojection), and a morphism new_vertex → v (the universal
        # map to each vertex). This makes new_vertex a "weak colimit".
        new_morphisms = []
        if self.category is not None:
            for v in verts:
                new_morphisms.append({
                    'source': v,
                    'target': new_vertex,
                    'morphism': f"coproj_{v}_to_{new_vertex}",
                })
                new_morphisms.append({
                    'source': new_vertex,
                    'target': v,
                    'morphism': f"univ_{new_vertex}_to_{v}",
                })

        return {
            'new_vertex': new_vertex,
            'new_hyperedges': new_hyperedges,
            'new_morphisms': new_morphisms,
        }

    def apply_generation(self, fillers: List[Dict[str, Any]]) -> None:
        """
        Apply the generated fillers to the hypergraph and category.
        """
        for filler in fillers:
            new_v = filler['new_vertex']
            self.hypergraph.vertices.add(new_v)
            for i, edge in enumerate(filler['new_hyperedges']):
                self.hypergraph.add_hyperedge(
                    f"gen_{new_v}_{i}",
                    edge,
                    weight=0.5
                )
            if self.category is not None:
                self.category.add_object(new_v)
                for morph in filler['new_morphisms']:
                    self.category.add_morphism(
                        morph['source'],
                        morph['target'],
                        morph['morphism']
                    )

    def generate_and_fill(self) -> Dict[str, Any]:
        """
        Full pipeline: detect missing simplices, generate fillers, apply them.

        Returns a summary of what was generated.
        """
        missing = self.detect_missing_simplices()
        if not missing:
            return {
                'status': 'complete',
                'message': 'No missing simplices detected. The category is already idempotent‑complete up to dimension 2.',
                'generated': 0,
            }

        fillers = []
        for simplex in missing[:self.max_generations]:
            filler = self.generate_filler(simplex)
            fillers.append(filler)

        self.apply_generation(fillers)

        return {
            'status': 'generated',
            'message': f'Generated {len(fillers)} new concepts to fill missing simplices.',
            'generated': len(fillers),
            'new_vertices': [f['new_vertex'] for f in fillers],
            'missing_simplices': [
                {'vertices': list(s.vertices), 'description': s.description}
                for s in missing[:self.max_generations]
            ],
        }

    def euler_characteristic_before_after(self) -> Dict[str, int]:
        """
        Compute the Euler characteristic before and after generation.
        χ = V - E + F (where F = number of filled triangles).
        """
        vertices = len(self.hypergraph.vertices)
        edges = len(self.hypergraph.hyperedges)
        # Estimate number of 2‑simplices (hyperedges of size ≥ 3)
        faces = sum(1 for e in self.hypergraph.hyperedges.values() if len(e) >= 3)
        chi_before = vertices - edges + faces
        # After generation (simulated by adding the missing count)
        missing = self.detect_missing_simplices()
        chi_after = (vertices + len(missing)) - (edges + len(missing) * 3) + (faces + len(missing))
        return {
            'chi_before': chi_before,
            'chi_after': chi_after,
            'missing_simplices': len(missing),
        }


# ============================================================================
# Factory
# ============================================================================

def topological_generation_pipeline(hypergraph) -> Dict[str, Any]:
    """
    Run the topological generation pipeline: detect gaps and fill them.

    Returns a summary of the generation process.
    """
    gen = TopologicalGenerator(hypergraph)
    result = gen.generate_and_fill()
    chi = gen.euler_characteristic_before_after()
    result['euler_characteristic'] = chi
    return result