#!/usr/bin/env python3
"""
Von Neumann Algebra – Non‑Commutative Observational Algebra for APEIRON
========================================================================
Optional module for Layer 2.

Implements a von Neumann algebra over the QuantumGraph, recognizing that
the order of observation affects the structure of knowledge. For certain
pairs of relations, [A, B] ≠ 0. The AI acknowledges that understanding
the "shape" of an object unavoidably disturbs information about its
"change", eliminating the illusion of an objective, static reality.

Mathematical Foundation
-----------------------
A von Neumann algebra M is a *-algebra of bounded operators on a Hilbert
space H, closed in the weak operator topology. Here:
- H is the space of 0‑cochains C⁰(H; F) (functions on vertices).
- Operators are generated by projection operators onto vertex stalks
  and the Dirac operator D from the spectral triple.
- The commutator [A, B] measures non‑simultaneous knowability.

The double commutant theorem M'' = M provides a closure property that
guarantees the algebra is generated by its projections. In Apeiron,
projections correspond to assertions about observable values, and the
non‑commutativity captures the context‑dependence of knowledge.

References
----------
.. [1] von Neumann, J. "Mathematical Foundations of Quantum Mechanics" (1955)
.. [2] Beniers, D. "Quantum Graph Module for APEIRON" (2025)
.. [3] Connes, A. "Noncommutative Geometry" (1994)
"""

import numpy as np
from typing import Dict, List, Tuple, Optional, Any, Set
from dataclasses import dataclass, field

try:
    from apeiron.layers.layer02_relational.hypergraph import Hypergraph
except ImportError:
    Hypergraph = None

try:
    from apeiron.layers.layer02_relational.quantum_graph import QuantumGraph
except ImportError:
    QuantumGraph = None


@dataclass
class Observable:
    """
    An observable in the von Neumann algebra: a self‑adjoint matrix
    acting on the Hilbert space of 0‑cochains.
    """
    name: str
    matrix: np.ndarray  # self‑adjoint matrix

    def __post_init__(self):
        # Ensure self‑adjointness
        if not np.allclose(self.matrix, self.matrix.conj().T):
            self.matrix = 0.5 * (self.matrix + self.matrix.conj().T)

    def expectation(self, state: np.ndarray) -> float:
        """Compute expectation value ⟨ψ|A|ψ⟩ for a pure state."""
        return float(np.real(state.conj().T @ self.matrix @ state))

    def commutator(self, other: 'Observable') -> np.ndarray:
        """Compute [A, B] = AB - BA."""
        return self.matrix @ other.matrix - other.matrix @ self.matrix

    def is_compatible_with(self, other: 'Observable',
                          threshold: float = 1e-10) -> bool:
        """Two observables are compatible (can be simultaneously known)
        if their commutator vanishes."""
        comm = self.commutator(other)
        return np.linalg.norm(comm, 'fro') < threshold

    def uncertainty_product(self, other: 'Observable', state: np.ndarray) -> float:
        """
        Compute ΔA · ΔB for a given state.
        By the Robertson inequality: ΔA · ΔB ≥ ½ |⟨[A,B]⟩|.
        """
        var_A = self.expectation(state ** 2) - self.expectation(state) ** 2
        var_B = other.expectation(state ** 2) - other.expectation(state) ** 2
        return float(np.sqrt(max(var_A, 0)) * np.sqrt(max(var_B, 0)))


class VonNeumannAlgebra:
    """
    A concrete von Neumann algebra generated by projection operators
    associated with vertices of the hypergraph.

    Parameters
    ----------
    hypergraph : Hypergraph
        The underlying knowledge hypergraph.
    quantum_graph : QuantumGraph, optional
        Pre‑built quantum graph; if None, a trivial one is constructed.
    """

    def __init__(self, hypergraph, quantum_graph=None):
        if Hypergraph is None:
            raise ImportError("Hypergraph module is required.")
        self.hypergraph = hypergraph
        self.quantum_graph = quantum_graph
        self._n = len(hypergraph.vertices)
        # Vertex‑indexed list
        self._vertex_list = sorted(hypergraph.vertices)
        self._vertex_idx = {v: i for i, v in enumerate(self._vertex_list)}

        # Build basic projection operators: P_v = |e_v⟩⟨e_v|
        self.projections: Dict[Any, Observable] = {}
        for v, i in self._vertex_idx.items():
            mat = np.zeros((self._n, self._n))
            mat[i, i] = 1.0
            self.projections[v] = Observable(f"P_{v}", mat)

        # Build Dirac operator from sheaf Laplacian (if available)
        self.dirac = self._build_dirac()
        if self.dirac is not None:
            self.dirac = Observable("D", self.dirac)

    def _build_dirac(self) -> Optional[np.ndarray]:
        """Construct Dirac operator D from the sheaf Laplacian."""
        try:
            from apeiron.layers.layer02_relational.sheaf_hypergraph import SheafHypergraph
            vertices = [f"v_{v}" for v in self._vertex_list]
            hyperedges = [{f"v_{v}" for v in e} for e in self.hypergraph.hyperedges.values()]
            if not vertices:
                return None
            shg = SheafHypergraph(vertices, hyperedges)
            L0 = shg.compute_sheaf_laplacian(order=0)
            eigenvalues, eigenvectors = np.linalg.eigh(L0)
            eigenvalues = np.maximum(eigenvalues, 0.0)
            return eigenvectors @ np.diag(np.sqrt(eigenvalues)) @ eigenvectors.T
        except Exception:
            return None

    def observable_from_function(self, values: Dict[Any, float]) -> Observable:
        """
        Build a diagonal observable from a function on vertices.
        """
        mat = np.diag([values.get(v, 0.0) for v in self._vertex_list])
        return Observable("f", mat)

    def check_non_commutativity(self, obs1: Observable, obs2: Observable) -> Dict[str, Any]:
        """
        Analyze whether two observables can be simultaneously known.

        Returns a dict with the commutator norm, compatibility, and
        a qualitative description.
        """
        comm = obs1.commutator(obs2)
        norm = float(np.linalg.norm(comm, 'fro'))
        compatible = norm < 1e-10
        return {
            'commutator_norm': norm,
            'compatible': compatible,
            'description': (
                'Observables commute — can be simultaneously known with arbitrary precision'
                if compatible else
                'Non‑commutative pair: observing one disturbs the other. '
                'No objective simultaneous reality.'
            ),
        }

    def global_commutativity_graph(self) -> Dict[str, Any]:
        """
        Build the commutativity graph among vertex projections.
        Two vertices are compatible if their projections commute
        (always true for diagonal projections, but non‑trivial when
        off‑diagonal contributions from the Dirac operator are included).
        """
        n = self._n
        compatible = np.zeros((n, n), dtype=bool)
        for i in range(n):
            for j in range(n):
                P_i = self.projections[self._vertex_list[i]]
                P_j = self.projections[self._vertex_list[j]]
                compatible[i, j] = P_i.is_compatible_with(P_j)
        # Count incompatible pairs
        incompat_pairs = []
        for i in range(n):
            for j in range(i + 1, n):
                if not compatible[i, j]:
                    incompat_pairs.append((self._vertex_list[i], self._vertex_list[j]))
        return {
            'compatible': compatible.tolist(),
            'num_incompatible_pairs': len(incompat_pairs),
            'incompatible_pairs': incompat_pairs,
            'fraction_compatible': float(np.mean(compatible)),
        }


# ============================================================================
# Factory
# ============================================================================

def von_neumann_analysis(hypergraph) -> Dict[str, Any]:
    """
    Perform non‑commutative analysis on a hypergraph.

    Returns a summary of non‑commutativity in the knowledge graph.
    """
    algebra = VonNeumannAlgebra(hypergraph)
    # Check non‑commutativity between Dirac operator and vertex projections
    results = {}
    if algebra.dirac is not None:
        for v, proj in algebra.projections.items():
            comm_check = algebra.check_non_commutativity(proj, algebra.dirac)
            if not comm_check['compatible']:
                results[f"D vs P_{v}"] = comm_check
    graph = algebra.global_commutativity_graph()
    return {
        'dirac_commutators': results,
        'commutativity_graph': graph,
    }